### ISSUE TITLE
请问应用闪退怎么办

### ISSUE THREAD

**Issue by pointm** [Foreverddb/FuckLegym#1]
_(:з」∠)_

**Comment by Foreverddb** [comment]
具体描述一下是安装时闪退还是使用过程中闪退，如果是使用过程中请说一下是什么具体操作和过程然后闪退的

**Comment by pointm** [comment]
> 具体描述一下是安装时闪退还是使用过程中闪退，如果是使用过程中请说一下是什么具体操作和过程然后闪退的

在打开软件输入好账号密码之后，在点击刷跑步或者刷签到的按钮的时候，应用闪退了

**Comment by Foreverddb** [comment]
这种情况很有可能是账号密码输错了，可以试着在乐键上面退出登陆再登陆检查一下是不是这个账号密码。

**Comment by pointm** [comment]
> 具体描述一下是安装时闪退还是使用过程中闪退，如果是使用过程中请说一下是什么具体操作和过程然后闪退的

顺便说一下，我的系统是鸿蒙，我同学的小米MIUI12.5.16也闪退了

**Comment by pointm** [comment]
> 这种情况很有可能是账号密码输错了，可以试着在乐键上面退出登陆再登陆检查一下是不是这个账号密码。

谢谢解答，但是我跟我室友试了账密，应该是没有问题的，最后还是闪退了

**Comment by Foreverddb** [comment]
> > 这种情况很有可能是账号密码输错了，可以试着在乐键上面退出登陆再登陆检查一下是不是这个账号密码。
> 
> 谢谢解答，但是我跟我室友试了账密，应该是没有问题的，最后还是闪退了

那么跑步界面的今日剩余里程和签到的活动有正常加载吗？

**Comment by pointm** [comment]
> > > 这种情况很有可能是账号密码输错了，可以试着在乐键上面退出登陆再登陆检查一下是不是这个账号密码。
> > 
> > 谢谢解答，但是我跟我室友试了账密，应该是没有问题的，最后还是闪退了
> 
> 那么跑步界面的今日剩余里程和签到的活动有正常加载吗？

我和我室友只是参加一下大四的体能班，没有剩余里程数哈，我们的签到活动应该是下个星期开![Screenshot_20220307_165139_com.ledreamer.zz.jpg](https://user-images.githubusercontent.com/49180699/156998694-15cf3bf8-5a70-4d82-957b-e97f005de39d.jpg)![Screenshot_20220307_165148_com.ledreamer.zz.jpg](https://user-images.githubusercontent.com/49180699/156998703-d384b513-7c63-44f3-af74-e4497116b5d6.jpg)

**Comment by Foreverddb** [comment]
😂我这还是第一次见体能班这种情况，那应该是现在无法获取数据所以出错了，如果你不介意的话可以邮箱私发我一下你的乐健账号密码让我进行测试修改吗？我的邮箱是835236331@qq.com，我保证仅用于软件测试。介意的话可以不发，我测试好了通知你。

**Comment by pointm** [comment]
> 😂我这还是第一次见体能班这种情况，那应该是现在无法获取数据所以出错了，如果你不介意的话可以邮箱私发我一下你的乐健账号密码让我进行测试修改吗？我的邮箱是835236331@qq.com，我保证仅用于软件测试。介意的话可以不发，我测试好了通知你。

好的，谢谢大佬，你也是电子科大的吧，修好了请你吃饭

**Comment by Foreverddb** [comment]
我是沙河的😂你的账号在我手机上也会闪退，初步判断的确是数据获取问题

**Comment by pointm** [comment]
> 我是沙河的😂你的账号在我手机上也会闪退，初步判断的确是数据获取问题

好吧，，

**Comment by Foreverddb** [comment]
已解决问题，请到release下载最新版本。我已删除本地存在的你的乐健账号密码，请尽快更改你的乐健用户名与密码。

**Comment by pointm** [comment]
> 已解决问题，请到release下载最新版本。我已删除本地存在的你的乐健账号密码，请尽快更改你的乐健用户名与密码。

好的，谢谢hxd
