### ISSUE TITLE
[bug] 3.1.0版 课程签到出现闪退

### ISSUE THREAD

**Issue by raphael-le** [Foreverddb/FuckLegym#10]
今天上午十点二十的伤病护理，十点二十之前是可以点进课程签到这跟个板块的。但是十点二十一到，我点进课程签到就会闪退出程序。但刷跑步和活动签到是可以签到。
btw，这个程序太好用了，学弟真厉害哈哈哈

**Comment by Foreverddb** [comment]
请问是点进去就直接闪退吗？请具体描述一些其他细节，今晚上要上课，有时间再修复

**Comment by raphael-le** [comment]
对，就是一点课程签到，会出现一瞬间课程签到的页面（并没有加载出我的课程的具体信息），然后就卡出去了。

**Comment by Foreverddb** [comment]
了解，之后有时间我会试着修复

**Comment by callG** [comment]
> 请问是点进去就直接闪退吗？请具体描述一些其他细节，今晚上要上课，有时间再修复

这个问题发生在二次签到时，二次签到是手机上显示一个二维码让老师扫码。

**Comment by Foreverddb** [comment]
已更新，请到release下载最新版
