### ISSUE TITLE
[bug] ColorOS 打开安装包卡死

### ISSUE THREAD

**Issue by callG** [Foreverddb/FuckLegym#11]
OPPO Reno5 Pro ColorOS V11.1 打开 [Releases](https://github.com/Foreverddb/FuckLegym/releases/) 下的任一安装包都会导致安装包管理器卡死，并在数秒后自动退出。
![打开安装包后卡死在此界面](https://user-images.githubusercontent.com/34684397/157234591-c7ac7541-3e85-465d-8870-0e2a5e016560.jpg)

**Comment by Foreverddb** [comment]
可以尝试使用apk安装器安装
![5932ef0f97f41df3](https://user-images.githubusercontent.com/60093071/157236059-c185a062-b75f-4a46-9e40-2044e524accd.jpg)

**Comment by Foreverddb** [comment]
已经按这个方法试了，请到release中下载最新版本试一试

**Comment by callG** [comment]
> 已经按这个方法试了，请到release中下载最新版本试一试

还是没用，不过我自己改了一点东西，然后用 android studio 编译了一下就可以安装了，之后我再找找原因吧。
