### ISSUE TITLE
安卓12闪退

### ISSUE THREAD

**Issue by callG** [Foreverddb/FuckLegym#11]
安卓12（color os 12），3.7.0 & 3.7.0 --fix 版本均闪退

**Comment by Findx3** [comment]
我也遇到了这样的问题

**Comment by Foreverddb** [comment]
请前往[release](https://github.com/Foreverddb/FuckLegym/releases/tag/3.7.1)下载最新版试试

**Comment by Reb-lhz** [comment]
3.7.1在安卓12MIUI13上因自身原因闪退

**Comment by laidu1235** [comment]
3.7.1闪退.0正常

**Comment by Foreverddb** [comment]
大家下载这个包试试？[点此](https://github.com/Foreverddb/FuckLegym/releases/tag/0.0.0)

**Comment by Reb-lhz** [comment]
> 

MIUI13不闪退了

**Comment by laidu1235** [comment]
UI4.1正常

**Comment by callG** [comment]
> 大家下载这个包试试？[点此](https://github.com/Foreverddb/FuckLegym/releases/tag/0.0.0)

这个不闪退，3.7.1没试
