### ISSUE TITLE
关于活动显示数量的问题

### ISSUE THREAD

**Issue by Workload1** [Foreverddb/FuckLegym#13]
大佬，现在软件中活动签到好像只显示10个，但体质提升课和自由锻炼的数量远不止10个，这会导致有时候找不到自己要签到的活动。请问可以增加一下活动签到的显示数量吗？谢谢大佬！

**Comment by Foreverddb** [comment]
了解，有时间就更新

**Comment by Foreverddb** [comment]
已更新，请到release中下载最新版
