### ISSUE TITLE
API文档求共享

### ISSUE THREAD

**Issue by Bill-Haku** [Foreverddb/FuckLegym#13]
你好，iOS和macOS版的1.0版本的iLegym已经做好了，但是我发现上次你给我分享的乐健API的Postman页面似乎已经失效了，我没能及时保存。希望能够再分享给我一次。谢谢！

**Comment by Foreverddb** [comment]
尽快保存，过一段时间我就关掉：https://documenter.getpostman.com/view/17744453/UVysxwBc
