### ISSUE TITLE
某些安卓11手机无法安装

### ISSUE THREAD

**Issue by duandaxian** [Foreverddb/FuckLegym#14]
有两个安卓11机型貌似现在还是安装不上，oppofind 3 Pro 和一加9  就是卡在安装界面不动了
![-fb73bdf011b3f6a](https://user-images.githubusercontent.com/95346847/157569147-f6f5f4b8-62ad-4861-8334-68e227bd6c38.jpg)

**Comment by duandaxian** [comment]
一直持续这个界面，然后会闪退

**Comment by Foreverddb** [comment]
目前确实oppo系的手机安装一直有问题😣在找原因，可能要一段时间才能修

**Comment by Foreverddb** [comment]
已解决，请到[release](https://github.com/Foreverddb/FuckLegym/releases/)安装最新版

**Comment by duandaxian** [comment]
大佬大佬，那个OPPOfindx3Pro怎么回事啊，太安全了？😂

Uploading QQ视频_0cc83e2f4266e3c5356c78e4af2fffeb1646901513.mp4…

**Comment by duandaxian** [comment]
谢谢大佬，好了，解决了❤️
