### ISSUE TITLE
求求各位大佬救我狗命

### ISSUE THREAD

**Issue by nwj18735634480** [Foreverddb/FuckLegym#14]
本人是西南交带的一个渣渣，交带这学期有太极和健身跑两个签到活动，本渣手贱，数次报名但未签到，现在乐健显示达到报名次数上限，不允许再报名，故在此跪求各位大佬看看能否破了这个上限或者把报了没签到的记录删除，求求各位大佬救救我的体育，给💰，请客吃饭，给你们当狗都行，本渣不想体育挂科

**Comment by Foreverddb** [comment]
抱歉，这个限制是乐健后台服务器设下的限制，确实没有办法破解，只有靠你自己按时签到了
