### ISSUE TITLE
地图

### ISSUE THREAD

**Issue by zby946** [Foreverddb/FuckLegym#15]
"中国民用航空飞行学院（广汉校区）": {
    "latitude": [30.94649, 30.94649, 30.947254, 30.947309, 30.94765, 30.949255, 30.949886, 30.94989, 30.951109, 30.950566, 30.949113, 30.950336, 30.94972, 30.948984, 30.947843, 30.947199, 30.946821, 30.949195, 30.94736, 30.950815],
    "longitude": [104.310407, 104.308604, 104.309087, 104.308186, 104.31045, 104.309886, 104.309135, 104.307483, 104.306668, 104.308041, 104.306915, 104.307526, 104.306539, 104.305938, 104.306528, 104.306013, 104.306775, 104.305531, 104.309146]
  }

**Comment by zby946** [comment]
"中国民用航空飞行学院（广汉校区）": {
    "latitude": [104.310407, 104.308604, 104.309087, 104.308186, 104.31045, 104.309886, 104.309135, 104.307483, 104.306668, 104.308041, 104.306915, 104.307526, 104.306539, 104.305938, 104.306528, 104.306013, 104.306775, 104.305531, 104.309146],
    "longitude": [30.94649, 30.94649, 30.947254, 30.947309, 30.94765, 30.949255, 30.949886, 30.94989, 30.951109, 30.950566, 30.949113, 30.950336, 30.94972, 30.948984, 30.947843, 30.947199, 30.946821, 30.949195, 30.94736, 30.950815]
  }

**Comment by zby946** [comment]
我是笨比最开始经纬度搞反了

**Comment by Foreverddb** [comment]
收到，明天有时间修复负数跑步和更新地图

**Comment by Neymar1207** [comment]
put("攀枝花学院（1207）", new HashMap<String, double[]>(){{                put("latitude", new double[]{101.721834,101.721655,101.721462,101.721053,101.720777,101.720514,101.72016,101.719844,101.719365,101.718925,101.718287,101.717949,101.717906,101.718099,101.718636,101.718925,101.71914,101.71929,101.719553,101.720095,101.720256,101.720449,101.72061,101.720851,101.720975,101.721243,101.721468,101.721736,101.7219,101.721913,101.721919,101.721833,101.721828});                put("lontitude", new double[]{26.567642,26.567757,26.567915,26.568246,26.568458,26.568664,26.568947,26.569192,26.569355,26.569235,26.568894,26.569278,26.568208,26.568083,26.568016,26.567815,26.567656,26.567436,26.567148,26.566639,26.566524,26.566519,26.566663,26.566735,26.566788,26.566874,26.566898,26.566994,26.567172,26.567085,26.567229,26.567517,26.567627});                put("base", new double[]{101.721834,26.567642});            }});
}

**Comment by Foreverddb** [comment]
已更新地图

**Comment by M1sceden4** [comment]
"西南石油大学（南充校区）":{
    "latitude":[30.824999,30.825128,30.825156,30.82511,30.825119,30.825064,30.824999,30.824953,30.824898,30.824746,30.824769,30.824801,30.82481,30.824953,30.824948,30.825008,30.825064,30.825091,30.825119,30.825073,30.825017],
    "longtitude":[106.12029,106.120376,106.120478,106.120607,106.120693,106.1208,106.12095,106.121025,106.121181,106.120789,106.120698,106.120543,106.120403,106.120226,106.120194,106.120226,106.120355,106.120317,106.120623,106.120789,106.120881]
  }

**Comment by Foreverddb** [comment]
已merge

**Comment by M1sceden4** [comment]
> 已merge

您好，刚刚更新了下地图之后好像出了点问题，每次点击选择跑步区域会退回到初始界面，我是HUAWEI MATE30

**Comment by M1sceden4** [comment]
> > 已merge
> 
> 您好，刚刚更新了下地图之后好像出了点问题，每次点击选择跑步区域会退回到初始界面，我是HUAWEI MATE30

代佬，具体流程是这样的，导入地图（显示导入成功，返回之前的页面），然后再点击选择跑步区域就会退回到主页，之后一直都是这样，是不是我刚刚添加的地图代码有点问题哦  呜

**Comment by Foreverddb** [comment]
> 

待我重新检查一下

**Comment by Foreverddb** [comment]
> 

待我重新检查一下

**Comment by Foreverddb** [comment]
> > > 已merge
> > 
> > 
> > 您好，刚刚更新了下地图之后好像出了点问题，每次点击选择跑步区域会退回到初始界面，我是HUAWEI MATE30
> 
> 代佬，具体流程是这样的，导入地图（显示导入成功，返回之前的页面），然后再点击选择跑步区域就会退回到主页，之后一直都是这样，是不是我刚刚添加的地图代码有点问题哦 呜

已修复

**Comment by zby946** [comment]
> 收到，明天有时间修复负数跑步和更新地图

大佬你好，为什么内个更新的中飞院地图没法用啊？

**Comment by niko272** [comment]
put("四川农业大学（雅安校区）", new HashMap<String, double[]>(){{
                put("latitude", new double[]{[103.002778](tel:103002778), [103.002668](tel:103002668), [103.002618](tel:103002618),  [103.002538](tel:103002538), [103.002456](tel:103002456), [103.002305](tel:103002305), [103.002289](tel:103002289), [103.002324](tel:103002324), [103.002377](tel:103002377), [103.002423](tel:103002423), [103.002493](tel:103002493), [103.002507](tel:103002507), [103.002617](tel:103002617), [103.002696](tel:103002696), [103.002822](tel:103002822), [103.002952](tel:103002952), [103.00306](tel:10300306), [103.002778](tel:103002778), [103.003206](tel:103003206), [103.003317](tel:103003317), [103.003348](tel:103003348), [103.003426](tel:103003426), [103.003515](tel:103003515), [103.003607](tel:103003607), [103.003582](tel:103003582), [103.00372](tel:10300372), [103.003721](tel:103003721), [103.003734](tel:103003734), [103.003723](tel:103003723), [103.003693](tel:103003693), [103.003683](tel:103003683), [103.003556](tel:103003556), [103.003537](tel:103003537), [103.003444](tel:103003444), [103.003293](tel:103003293), [103.00319](tel:10300319), [103.003062](tel:103003062), [103.00285](tel:10300285)});
                put("lontitude", new double[]{[29.979426](tel:29979426), [29.979419](tel:29979419), [29.979411](tel:29979411), [29.979378](tel:29979378), [29.979335](tel:29979335), [29.979201](tel:29979201), [29.979088](tel:29979088), [29.978943](tel:29978943), [29.978867](tel:29978867), [29.978822](tel:29978822), [29.978799](tel:29978799), [29.978768](tel:29978768), [29.978712](tel:29978712), [29.978667](tel:29978667), [29.978609](tel:29978609), [29.978531](tel:29978531), [29.978504](tel:29978504), [29.9794](tel:299794), [29.978397](tel:29978397), [29.978363](tel:29978363), [29.978352](tel:29978352), [29.97837](tel:2997837), [29.978401](tel:29978401), [29.978435](tel:29978435), [29.978417](tel:29978417), [29.978575](tel:29978575), [29.978616](tel:29978616), [29.978705](tel:29978705), [29.97881](tel:2997881), [29.97887](tel:2997887), [29.978917](tel:29978917), [29.978976](tel:29978976), [29.978989](tel:29978989), [29.97903](tel:2997903), [29.979118](tel:29979118), [29.97916](tel:2997916), [29.979239](tel:29979239), [29.97936](tel:2997936)});
                put("base", new double[]{[103.002778](tel:103002778), [29.979426](tel:29979426)});
            }});

**Comment by Foreverddb** [comment]
> > 收到，明天有时间修复负数跑步和更新地图
> 
> 大佬你好，为什么内个更新的中飞院地图没法用啊？

已修复
