### ISSUE TITLE
安装包推送错了，3.7.3推的还是3.7.2的包

### ISSUE THREAD

**Issue by ftdup01** [Foreverddb/FuckLegym#16]

**Comment by ftdup01** [comment]
![Screenshot_2022-04-08-15-17-43-308_com android browser](https://user-images.githubusercontent.com/45959230/162384510-a326e141-ad7b-4774-91fa-b5e4be68ea66.png)

**Comment by ftdup01** [comment]
![Screenshot_2022-04-08-15-17-35-249_com miui packageinstaller](https://user-images.githubusercontent.com/45959230/162384587-38240db9-c972-4c45-a85a-3a9ebe899059.png)

**Comment by ftdup01** [comment]
![Screenshot_2022-04-08-15-24-58-873_com miui packageinstaller](https://user-images.githubusercontent.com/45959230/162385493-a049dba7-678b-43d9-beff-467523f73d73.png)

**Comment by ftdup01** [comment]
@Foreverddb 推送错包了，显示3.7.3实际上是3.7.2的包

**Comment by ftdup01** [comment]
在release页面下载的3.7.2和3.7.3包的md5完全一样，推错包了

**Comment by Foreverddb** [comment]
包换好了，请前往release下载
