### ISSUE TITLE
活动签到功能不可用

### ISSUE THREAD

**Issue by pointm** [Foreverddb/FuckLegym#16]
![Screenshot_20220311_084414_com.ledreamer.zz.jpg](https://user-images.githubusercontent.com/49180699/157780265-3e1d64a3-5f6f-422c-9831-e13465db8d0a.jpg)![Screenshot_20220311_084426_central.stu.fucklegym.jpg](https://user-images.githubusercontent.com/49180699/157780269-05231feb-9137-4cbf-b3cc-1d6b8e804211.jpg)

点击活动签到选项后无法显示活动，也无法签到

**Comment by Foreverddb** [comment]
请首先检查一下账号密码是否正确，看看刷跑步的剩余里程之类的能否加载

**Comment by pointm** [comment]
> 请首先检查一下账号密码是否正确，看看刷跑步的剩余里程之类的能否加载

已经检查了，抱歉，是密码错误的缘故
