### ISSUE TITLE
[Feature request]刷跑步时多圈的路径增加随机扰动或偏移使其更真实

### ISSUE THREAD

**Issue by buzhibujuelb** [Foreverddb/FuckLegym#2]
跑道只有400米，路程一长时显示为同一条线容易被发现（且不同人跑出形状相同的路线也容易被怀疑）
![IMG_20220307_172051](https://user-images.githubusercontent.com/24644841/157003061-f4332d32-cc66-47b3-bd5c-5f53bb2407ea.jpg)
![IMG_20220307_172015](https://user-images.githubusercontent.com/24644841/157003064-4ed2397f-a632-48ff-80fd-0c8506a4a007.jpg)
以及可以加个生成随机路程长度，看到有人直接刷个3.00公里一点小数不带是否有点过于……

**Comment by Foreverddb** [comment]
是个好想法🤔我有时间加一下

**Comment by Foreverddb** [comment]
已更新该功能，请在[release](https://github.com/Foreverddb/FuckLegym/releases/)下载最新版
