### ISSUE TITLE
希望能总结一下相关API文档

### ISSUE THREAD

**Issue by Bill-Haku** [Foreverddb/FuckLegym#20]
希望作者能总结一下相关API文档，以便我来“练习“一下iOS端的开发

**Comment by Foreverddb** [comment]
行，晚上整一份出来

**Comment by Foreverddb** [comment]
api文档（里面有请求和响应的相关说明和示例）：https://documenter.getpostman.com/view/17744453/UVsHV8r1

**Comment by Foreverddb** [comment]
老哥加油，ios靠你了😘

**Comment by Bill-Haku** [comment]
好的感谢！已经开干了！
