### ISSUE TITLE
> [DdB's Legym_3.0.1.apk.zip](https://github.com/Foreverddb/FuckLegym/files/8469608/DdB.s.Legym_3.0.1.apk.zip) 这是旧版的软件，可以免费使用 没必要用最新的土豪专用版（乐

### ISSUE THREAD

**Issue by MoMXFL** [Foreverddb/FuckLegym#23]
> [DdB's Legym_3.0.1.apk.zip](https://github.com/Foreverddb/FuckLegym/files/8469608/DdB.s.Legym_3.0.1.apk.zip) 这是旧版的软件，可以免费使用 没必要用最新的土豪专用版（乐

别人作者辛辛苦苦做了几个月的东西，你白用这么久一句感谢没有现在还要反过来搞人家。

_Originally posted by @ldh-star in https://github.com/Foreverddb/FuckLegym/issues/22#issuecomment-1096024999_

理中客？理中客？理中客！
这么多次 commits 更新了什么呢？更新了收费功能 :)

**Comment by Foreverddb** [comment]
😓我寻思3.6.1之前的版本都是开源的吧，也应该有人fork了，自己去看看提交记录不好吗？

**Comment by MoMXFL** [comment]
行了行了，不折腾您了，溜了
