### ISSUE TITLE
对开发者的一些话

### ISSUE THREAD

**Issue by xywml** [Foreverddb/FuckLegym#26]
说实话看见开发者被喷也不太舒服，别人没义务免费给你开发软件使用，开发者被喷后选择公布老版本的做法也挺佩服的，其实我有个建议，是否可以将付费机制改为赞赏机制，或者加入广告之类的，一方面可以让那些喷的人闭嘴，另一方面也可以鼓励开发者更新维护。

**Comment by xywml** [comment]
整个赞赏用户免广告之类的哈哈

**Comment by david4958606** [comment]
真tm笑死我了，中国开源事业就是这样一步步毁在你们这些人手里的。

这个 foreverddb，最早fork的是 RisingEntropy 的“[FuckLegymApp](https://github.com/buzhibujuelb/FuckLegymApp)”，后来entropy老哥将仓库转为了私有，ddb就在GPLv3协议下继续进行开发（当时的仓库可见[buzhibujuelb/FuckLegym](https://github.com/buzhibujuelb/FuckLegym)，一段时间后，ddb 将开源代码删除，闭源了软件。这是违反GPLv3协议的，如有必要，我甚至可以跟据该协议起诉 ddb（案例：[OSCHINA](https://www.oschina.net/news/178100)）。

注：上述两个 GitHub 仓库分别是 buzhibujuelb fork 的 entropy 的版本和 ddb 的初始版本，因为这两个的原仓库均被删库，所以没有 fork 的标识，但是可以从 commit 记录中看出。

此外，ddb 的操作是删除了开源的 FuckLegym 仓库后又建了同名的仓库（本仓库）做发布页面，但因为闭源版本和此前的开源版本的代码实质上相同，所以仍然在GPL管辖范围内。

**Comment by ldh-star** [comment]
> entropy

你最伟大了，赶紧给世界开源事业做贡献去，别搁这儿来找存在感了

**Comment by Foreverddb** [comment]
> 真是笑死我了，中国开源事业就是这样一步步毁在你们这些人手里的。
> 
> 这个 foreverddb，最早fork的是 RisingEntropy 的“[FuckLegymApp](https://github.com/buzhibujuelb/FuckLegymApp)”，后来entropy老哥将仓库转为了私有，ddb就在GPLv3协议下继续进行开发（当时的仓库可见[buzhibujuelb/FuckLegym](https://github.com/buzhibujuelb/FuckLegym)，一段时间后，ddb 将开源代码删除，闭源了软件。这是违反GPLv3协议的，如有必要，我甚至可以跟据该协议起诉 ddb（案例：[OSCHINA](https://www.oschina.net/news/178100)）。
> 
> 注：上述两个 GitHub 仓库分别是 buzhibujuelb fork 的 entropy 的版本和 ddb 的初始版本，因为这两个的原仓库均被删库，所以没有 fork 的标识，但是可以从 commit 记录中看出。
> 
> 此外，ddb 的操作是删除了开源的 FuckLegym 仓库后又建了同名的仓库（本仓库）做发布页面，但因为闭源版本和此前的开源版本的代码实质上相同，所以仍然在GPL管辖范围内。

不想带有什么攻击性，理性讨论，闭源自己开源的代码需要遵守LICENSE吗?

**Comment by david4958606** [comment]
> > 真是笑死我了，中国开源事业就是这样一步步毁在你们这些人手里的。
> > 这个 foreverddb，最早fork的是 RisingEntropy 的“[FuckLegymApp](https://github.com/buzhibujuelb/FuckLegymApp)”，后来entropy老哥将仓库转为了私有，ddb就在GPLv3协议下继续进行开发（当时的仓库可见[buzhibujuelb/FuckLegym](https://github.com/buzhibujuelb/FuckLegym)，一段时间后，ddb 将开源代码删除，闭源了软件。这是违反GPLv3协议的，如有必要，我甚至可以跟据该协议起诉 ddb（案例：[OSCHINA](https://www.oschina.net/news/178100)）。
> > 注：上述两个 GitHub 仓库分别是 buzhibujuelb fork 的 entropy 的版本和 ddb 的初始版本，因为这两个的原仓库均被删库，所以没有 fork 的标识，但是可以从 commit 记录中看出。
> > 此外，ddb 的操作是删除了开源的 FuckLegym 仓库后又建了同名的仓库（本仓库）做发布页面，但因为闭源版本和此前的开源版本的代码实质上相同，所以仍然在GPL管辖范围内。
> 
> 不想带有什么攻击性，理性讨论，闭源自己开源的代码需要遵守LICENSE吗?

请看上文我提供的案例，一日GPL，终生GPL。

**Comment by david4958606** [comment]
你如果最开始选用了宽松式许可证（比如 MIT 许可）那我无话可说，但你用的是GPL。

**Comment by Foreverddb** [comment]
> 你如果最开始选用了宽松式许可证（比如 MIT 许可）那我无话可说，但你用的是GPL。

那行，这个确实是我的问题，等两天我自己开源。但是也希望你能够像今天这样，好好指出问题，而不是昨天那样上来先极具攻击性地喷一通。

**Comment by david4958606** [comment]
> > 你如果最开始选用了宽松式许可证（比如 MIT 许可）那我无话可说，但你用的是GPL。
> 
> 那行，这个确实是我的问题，等两天我自己开源。但是也希望你能够像今天这样，好好指出问题，而不是昨天那样上来先极具攻击性地喷一通。

我认为我昨天的言论只是指出了你的不当之处，如果你感觉被冒犯，我在此向你道歉。
