### ISSUE TITLE
吃相未免有点难看

### ISSUE THREAD

**Issue by KIrayamoto** [Foreverddb/FuckLegym#27]
为了赚这点钱忙前忙后这么久可真是辛苦你了，找个厂上班不香吗
或许早在仓库闭源的时候我就该意识到你的动机不纯，一个仓库里面只有一个readme可太牛了😅

**Comment by Foreverddb** [comment]
行行行，合着我当初就不该先开源出来。你看看fake location仓库里是不是也只有readme?咋不去喷人家来这喷我个电子厂员工?

**Comment by CLOUDERHEM** [comment]
这个软件会收集你的一些信息。包括手机号，学校和学院，以及设备信息。

**Comment by KIrayamoto** [comment]
> 行行行，合着我当初就不该先开源出来。你看看fake location仓库里是不是也只有readme?咋不去喷人家来这喷我个电子厂员工?

你开啥源啊？不是你fork了别人的开源仓库吗？

**Comment by Foreverddb** [comment]
算了算了，不跟人吵了，希望你好好阅读一下这个仓库readme的声明部分，而且我一会儿重新开源了你自己看看有几句和我fork的那个仓库是一样的，到时候希望你能给个道歉。

**Comment by KIrayamoto** [comment]
> 算了算了，不跟人吵了，希望你好好阅读一下这个仓库readme的声明部分，而且我一会儿重新开源了你自己看看有几句和我fork的那个仓库是一样的，到时候希望你能给个道歉。

我为什么要道歉，说你闭源恰烂钱难道有错吗😅

**Comment by Foreverddb** [comment]
要是闭源就是恰烂钱的话，我同样的一句话话，当时开源我图个啥，不如不开，开了之后闭源被人喷，早知道最开始不开了

**Comment by Foreverddb** [comment]
已开源，自己鉴定吧

**Comment by KIrayamoto** [comment]
> 要是闭源就是恰烂钱的话，我同样的一句话，当时开源我图个啥，不如不开，开了之后闭源被人喷，早知道最开始不开了

你要是一开始就是闭源，完全自主开发，那自然爱怎么样怎么样。
但是你既然选择了使用开源项目选择了使用github，那就得老老实实按规则来

**Comment by Foreverddb** [comment]
> > 要是闭源就是恰烂钱的话，我同样的一句话，当时开源我图个啥，不如不开，开了之后闭源被人喷，早知道最开始不开了
> 
> 你要是一开始就是闭源，完全自主开发，那自然爱怎么样怎么样。 但是你既然选择了使用开源项目选择了使用github，那就得老老实实按规则来


现在我开源了，但不是因为这原因，github从未有过开源后不允许闭源的规则，连安卓系统都在逐渐走向闭源。有开闭源约束力的只有许可证，希望下次你找问题能找到点子上。

**Comment by huangzm1** [comment]
我不懂你们的规则，不好意思，不过其实我觉得收费还是可以的，只要便宜还是能接受的，毕竟维护服务器（我不知道，瞎说的，不懂这些）应该要钱吧

**Comment by KIrayamoto** [comment]
> 我不懂你们的规则，不好意思，不过其实我觉得收费还是可以的，只要便宜还是能接受的，毕竟维护服务器（我不知道，瞎说的，不懂这些）应该要钱吧

除了作者想赚钱，这种工具性质的软件有任何使用他自己的服务器的必要吗？
他甚至还加入了强制检测更新和远程停用来让你用不了老版本🤣

**Comment by Foreverddb** [comment]
> > 我不懂你们的规则，不好意思，不过其实我觉得收费还是可以的，只要便宜还是能接受的，毕竟维护服务器（我不知道，瞎说的，不懂这些）应该要钱吧
> 
> 除了作者想赚钱，这种工具性质的软件有任何使用的服务器的必要吗？ 他甚至还加入了强制检测更新和远程停用来让你用不了老版本🤣

你这么说那工具性质的软件也没有任何让人免费使用的必要吧?没有服务器难道没有开发成本?不收费是情分不是本分，别人开发免费是别人的事，这不能成为站在道德制高点上指责收费的理由。不然你要不直接说大家别上班得了，反正上班也是因为员工想赚钱。
又要马儿跑得快，又要马儿不吃草，你觉得到底是谁在搞垮开源?

**Comment by KIrayamoto** [comment]
> > > 我不懂你们的规则，不好意思，不过其实我觉得收费还是可以的，只要便宜还是能接受的，毕竟维护服务器（我不知道，瞎说的，不懂这些）应该要钱吧
> > 
> > 
> > 除了作者想赚钱，这种工具性质的软件有任何使用的服务器的必要吗？ 他甚至还加入了强制检测更新和远程停用来让你用不了老版本🤣
> 
> 你这么说那工具性质的软件也没有任何让人免费使用的必要吧?没有服务器难道没有开发成本?不收费是情分不是本分，别人开发免费是别人的事，这不能成为站在道德制高点上指责收费的理由。不然你要不直接说大家别上班得了，反正上班也是因为员工想赚钱。 又要马儿跑得快，又要马儿不吃草，你觉得到底是谁在搞垮开源?

就您写的这点东西还出来收钱也未免太看得起自己了吧？况且您在软件开头写的可是**仅用于学习**，您学习软件开发还需要向别人收钱吗？

**Comment by Foreverddb** [comment]
> > > > 我不懂你们的规则，不好意思，不过其实我觉得收费还是可以的，只要便宜还是能接受的，毕竟维护服务器（我不知道，瞎说的，不懂这些）应该要钱吧
> > > 
> > > 
> > > 除了作者想赚钱，这种工具性质的软件有任何使用的服务器的必要吗？ 他甚至还加入了强制检测更新和远程停用来让你用不了老版本🤣
> > 
> > 
> > 你这么说那工具性质的软件也没有任何让人免费使用的必要吧?没有服务器难道没有开发成本?不收费是情分不是本分，别人开发免费是别人的事，这不能成为站在道德制高点上指责收费的理由。不然你要不直接说大家别上班得了，反正上班也是因为员工想赚钱。 又要马儿跑得快，又要马儿不吃草，你觉得到底是谁在搞垮开源?
> 
> 就您写的这点东西还出来收钱也未免太看得起自己了吧？况且您在软件开头写的可是**仅用于学习**，您学习软件开发还需要向别人收钱吗？

行行行，你是大佬，技术没你高超的不配收钱。况且这东西本来也不见得是什么必要的东西啊，别人想给钱就给，本来就是作弊在跑步还能说是作弊软件的问题?🤔
