### ISSUE TITLE
请添加四川农业大学都江堰校区

### ISSUE THREAD

**Issue by Phntom-Menace** [Foreverddb/FuckLegym#27]
[四川农业大学（都江堰校区）.txt](https://github.com/Foreverddb/FuckLegym/files/8258226/default.txt)

**Comment by Foreverddb** [comment]
已添加

**Comment by Phntom-Menace** [comment]
> 已添加
之前有一个逗号出问题了麻烦改一下刚刚更新了文档

**Comment by Foreverddb** [comment]
更新的时候已经帮你改了
