### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by ldh-star** [Foreverddb/FuckLegym#28]
希望可以作者大大可以新增用户偏好的功能，不用每次选择哪一个校区哪一个路线图（最好是那种每天进去点一个按钮就能直接上传每日跑步）。我也是乐健跑步的受害者，并且熟悉安卓开发，有兴趣加入你的项目共同开发。

**Comment by Foreverddb** [comment]
可以啊，欢迎大佬加入项目

**Comment by ldh-star** [comment]
留个QQ什么的？
