### ISSUE TITLE
好好好

### ISSUE THREAD

**Issue by ken-0** [Foreverddb/FuckLegym#3]
原来那个FuckLegymApp有点难用，本来打算自己fork下来改一下的
感谢大佬！把我想加的功能都加上了
最后支持正义赛马娘引流

**Comment by Foreverddb** [comment]
![Uploading A8C9AEB7A8AD0E08F932FE5D45560835.jpg…]()

**Comment by Foreverddb** [comment]
![A8C9AEB7A8AD0E08F932FE5D45560835](https://user-images.githubusercontent.com/60093071/157029462-df22b47f-e909-441d-a572-0a65a445fead.jpg)
