### ISSUE TITLE
最新版本依然闪退

### ISSUE THREAD

**Issue by pointm** [Foreverddb/FuckLegym#33]
十分感谢作者的修复，但是最新的应用依然在华为p30，鸿蒙系统上面闪退，现已回退到老版本进行使用。

**Comment by Foreverddb** [comment]
我换了个安装包，你再去release下载试试看？我在华为mate20上试着没问题

**Comment by pointm** [comment]
> 我换了个安装包，你再去release下载试试看？我在华为mate20上试着没问题

已经确认即使重新下载，3.4.1-fix与3.4.0华为p30依然闪退，3.2.0没有啥子问题_(:з」∠)_

**Comment by Foreverddb** [comment]
又更了个3.4.2版本，理论上这次应该没问题了

**Comment by pointm** [comment]
> 又更了个3.4.2版本，理论上这次应该没问题了

可以成功进入了，谢谢啦
