### ISSUE TITLE
获取活动时由于存储活动的数据类型为hashmap导致部分活动缺失

### ISSUE THREAD

**Issue by Suomy213** [Foreverddb/FuckLegym#35]
![Screenshot_2022-03-17-19-02-24-13_01c3e1b7d21445b](https://user-images.githubusercontent.com/26904283/158795751-0954ef02-753a-4c58-a19b-e5bc35b13986.jpg)
如图，两活动名称一样，hashmap的使用导致只会显示这两个活动中的其中一个
<img width="233" alt="image" src="https://user-images.githubusercontent.com/26904283/158795912-4057e0ac-04f2-4336-a7b4-6475cdc7acdc.png">

**Comment by Suomy213** [comment]
一个可行的解决方法，键和值对调

**Comment by Foreverddb** [comment]
了解，目前一些模块正在重构，可能需要一定时间来解决

**Comment by Foreverddb** [comment]
最新版已修复，请前往release下载
