### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by duandaxian** [Foreverddb/FuckLegym#44]
活动签到获取不到活动，鸿蒙手机
![Screenshot_20220319_093247_central stu fucklegym](https://user-images.githubusercontent.com/95346847/159101584-37482e7a-3630-4c02-b3e5-29022e60b796.jpg)

**Comment by Foreverddb** [comment]
了解，稍后修复

**Comment by Foreverddb** [comment]
已修复，请前往[release](https://github.com/Foreverddb/FuckLegym/releases/tag/3.5.2)下载
