### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by xywml** [Foreverddb/FuckLegym#46]
输入账号密码后登陆失败

**Comment by Foreverddb** [comment]
请说明使用的软件版本和具体情况

**Comment by xywml** [comment]
软件版本3.5.2和3.5.0，都试过，机型是k20pro，账号密码正确但提示登陆失败

**Comment by Foreverddb** [comment]
了解，稍后修复

**Comment by Foreverddb** [comment]
请到[release](https://github.com/Foreverddb/FuckLegym/releases/tag/3.5.3)下载最新版试试有没有问题

**Comment by xywml** [comment]
还是不能登陆，应该是我账号问题，3.5.0一下版本可以登陆，然后别人的账号在3.5.0以上版本没有问题

**Comment by Foreverddb** [comment]
已更新，请在app内接收更新推送
