### ISSUE TITLE
最新版本好像引用报错了

### ISSUE THREAD

**Issue by conceay** [Foreverddb/FuckLegym#55]
![image](https://user-images.githubusercontent.com/76985627/159147888-77b24da7-31b1-4088-8358-48a21a1a0c6e.png)
这个ldh的引用 好像报错了

**Comment by Foreverddb** [comment]
改一下引用路径就行了。仓库里的是开发版，不一定稳定。

**Comment by conceay** [comment]
好，谢谢大佬
