### ISSUE TITLE
请问跑步的公里数是上传的 runpoints 计算出来的吗？

### ISSUE THREAD

**Issue by niusme** [Foreverddb/FuckLegym#58]
请问跑步的公里数是上传的 runpoints 计算出来的吗？ 还是说 是单纯按照用户给定的范围 随机变化的？

**Comment by Foreverddb** [comment]
根据用户选择的范围随机变化，但是路径会根据实际路线和路程计算。比如用户选择2公里，路线是绕400操场的一圈，实际刷上的路线就会是计算出的绕操场5圈

**Comment by niusme** [comment]
再请问一下作者，我看到常见问题有说，上传跑步成绩的时候会上传设备信息，我在该段代码没有找到有关设备的信息，还望作者告知。我是打算做一个自动打卡的放服务器上，然后把自己的设备信息放入，这样就可以解放双手了.


` public static UploadStatus uploadRunningDetail(String accessToken, String limitationsGoalsSexInfoId, String semesterId, double totMileage, double validMileage, Date startTime, Date endTime, String map, String type) throws IOException {
        //这函数啥也不管，只管上传，检查数据是否安全不是它的事
        HashMap<String, String> header = new HashMap<>();
        header.put("Content-type", "application/json");
        header.put("Authorization", "Bearer " + accessToken);
        Random random = new Random(System.currentTimeMillis());
        //随机偏移一定的跑步路程避免整数
        double offset = random.nextDouble() / 100;
        if (totMileage >= 3.5) {
            totMileage -= offset;
            validMileage -= offset;
        } else {
            totMileage += offset;
            validMileage += offset;
        }
        JSONObject content = new JSONObject();
        double pace = 0.5 + random.nextInt(6) / 10.0;
        content.put("paceRange", pace);
        content.put("totalMileage", totMileage);
        content.put("limitationsGoalsSexInfoId", limitationsGoalsSexInfoId);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        content.put("endTime", formatter.format(endTime));
        content.put("startTime", formatter.format(startTime));
        content.put("effectiveMileage", validMileage);
        content.put("semesterId", semesterId);
        content.put("scoringType", 1);
        content.put("signPoint", new JSONArray());
        content.put("totalPart", 1);
        int calorie = (int) (totMileage * CALORIE_PER_MILEAGE);
        content.put("calorie", calorie);
        ArrayList<HashMap<String, String>> runPoints = new ArrayList<>();
        try {
            ArrayList<Pair<Double, Double>> genPoints = PathGenerator.genRegularRoutine(map, totMileage);
            for (Pair<Double, Double> point : genPoints) {
                HashMap<String, String> tmp = new HashMap<>();
                tmp.put("latitude", point.getKey().toString());
                tmp.put("longitude", point.getValue().toString());
                runPoints.add(tmp);
            }
        }catch (Exception e){
            e.printStackTrace();
            return UploadStatus.FAIL;
        }
        int keeptime = (int) (endTime.getTime() - startTime.getTime()) / 1000;
        content.put("keepTime", keeptime);
        content.put("routineLine", runPoints);
        content.put("type", type);
        int paceNumber = (int) (totMileage * 1000 / pace / 2);
        content.put("paceNumber", paceNumber);
        content.put("effectivePart", 1);
        content.put("gpsMileage", totMileage);
        content.put("uneffectiveReason", "");
        int avePace = ((int) ((endTime.getTime() - startTime.getTime()) / 1000 / totMileage)) * 1000;
        content.put("avePace", avePace);
        //生成关于本次跑步数据的SHA1签名
        content.put("signDigital", Encrypter.getSha1(validMileage
                + "1"
                + formatter.format(startTime)
                + calorie
                + avePace
                + keeptime
                + paceNumber
                + totMileage
                + "1" + Encrypter.run_salt));


        //System.out.println(content.toString());return UploadStatus.NOTLOGIN;
        JSONObject res = postForReturn(URL_UPLOAD_RUNNINGDETAIL, header, content.toString());
        Log.d("runRes", "uploadRunningDetail: " + res.toString());
        //System.out.println(res.toString());
        //{"code":0,"data":true}
        if (res.getBoolean("data")) return UploadStatus.SUCCESS;
        else return UploadStatus.FAIL;
    }`
