### ISSUE TITLE
关于我上传了跑步，但是有效里程数为0这件事

### ISSUE THREAD

**Issue by apprentice4** [Foreverddb/FuckLegym#59]
虽然跑步上传了里程数，三个指标应该都是符合要求的，但是最终结果显示就是有效路程为0，大佬可以优化一下嘛

**Comment by Foreverddb** [comment]
目前来说为了防止刷多了引起注意，如果已经超过了本学期要求里程的话是会限制有效里程的，后续版本会解除限制

**Comment by apprentice4** [comment]
好的，谢谢佬
