### ISSUE TITLE
求赛马娘原图

### ISSUE THREAD

**Issue by WiththeWindT** [Foreverddb/FuckLegym#7]
大佬你好，非常喜欢课程签到页面的赛马娘简笔画，在各大网站识图都没找到原图，因此在这里留个言，由于我是第一次用github，不知道怎么看回复，大佬方便的话能否直接加下我的qq或者发到我的qq邮箱里--谢谢！1026518542
不胜感激

**Comment by Foreverddb** [comment]
已发
