### ISSUE TITLE
川北医学院高坪校区地图

### ISSUE THREAD

**Issue by Wsz21** [Foreverddb/FuckLegym#8]
106.127666，30.779113
106.127628，30.778952
106.127483，30.778722
106.127462，30.778643
106.127526，30.7785
106.12758，30.778385
106.127655，30.778279
106.127741，30.778229
106.127853，30.778201
106.127977，30.778192
106.128095，30.778224
106.128116，30.778298
106.12817，30.778335
106.128229，30.778404
106.128234，30.778445
106.12824，30.7785
106.12824，30.778537
106.128277，30.778583
106.128277，30.778657
106.128304，30.778712
106.128309，30.778745
106.128315，30.778777
106.12832，30.7788
106.128331，30.778842
106.128352，30.778878
106.128374，30.77892
106.12839，30.778952
106.12839，30.778971
106.128433，30.779007
106.128449，30.77904
106.12847，30.779095
106.128492，30.779137
106.128524，30.779178
106.12854，30.779215
106.128567，30.779238
106.128572，30.779284
106.128561，30.779307
106.128583，30.779349
106.128572，30.779413
106.128599，30.779441
106.128599，30.779464
106.12861，30.779505
106.128626，30.779519
106.128647，30.779542
106.128631，30.779579
106.128631，30.779611
106.128647，30.779634
106.128647，30.779657
106.128647，30.779694
106.128679，30.779773
106.12869，30.779814
106.128717，30.779879
106.128749，30.779897
106.12876，30.779938
106.128739，30.779989
106.128674，30.780026
106.128626，30.780049
106.128529，30.780067
106.128449，30.780077
106.128401，30.780077
106.128336，30.780067
106.128288，30.780067
106.12824，30.780067
106.128197，30.780072
106.128132，30.780063
106.128084，30.780063
106.128041，30.780063
106.127966，30.780044
106.127896，30.780026
106.127864，30.779998
106.127848，30.779966
106.127794，30.779948
106.127762，30.779874
106.127768，30.779819
106.127757，30.779782
106.127757，30.779745
106.127725，30.779703
106.127746，30.77962
106.127725，30.779574
106.127703，30.779505
106.127682，30.779441
106.127676，30.779404
106.12766，30.779372
106.12766，30.77933
106.127639，30.779247
106.127607，30.779164
106.127591，30.779104
106.12758， 30.779049

**Comment by Foreverddb** [comment]
收到，明天有时间的话就更新

**Comment by Wsz21** [comment]
大佬，我自己搞了4个小时都没弄懂怎么自己fork，确实不会编程，只能麻烦下你了QAQ，

**Comment by Wsz21** [comment]
> 收到，明天有时间的话就更新

谢谢大佬QAQ

**Comment by Foreverddb** [comment]
已更新，请在[release](https://github.com/Foreverddb/FuckLegym/releases/)下载最新版
