### ISSUE TITLE
西南石油大学地图

### ISSUE THREAD

**Issue by XiMoHuanHua** [Foreverddb/FuckLegym#9]
大佬我自己写完了，但是整了一上午也没搞懂怎么生成apk。QAQ只能来麻烦大佬了

put("西南石油大学（成都校区）", new HashMap<String, double[]>(){{
                put("latitude", new double[]{30.825302,30.825417,30.825445,30.825472,30.825509,30.825578,30.825633,30.825666,30.825716,30.825799,30.825878,30.825905,30.825951,30.826002,30.826053,30.826066,30.826117,30.826200,30.826269,30.826324,30.826361,30.826398,30.826467,30.826518, 30.826564, 30.826555, 30.826550, 30.826522, 30.826467,30.826421,30.826370,30.826343,30.826288,30.826260,30.826232,30.826209,30.826177,30.826103,30.826094,30.826062,30.826002,30.825951,30.825910,30.825859,30.825822,30.825785,30.825730,30.825647,30.825560,30.825454,30.825426,30.825394,30.825357,30.825339,30.825325,30.825302,30.825265,30.825274,30.825284,30.825306});
                put("lontitude", new double[]{104.184846,104.184878,104.184889,104.184889,104.184910,104.184926,104.184932,104.184948,104.184958,104.185007,104.185034,104.185039,104.185055,104.185060,104.185082,104.185093,104.185109,104.185141,104.185157,104.185135,104.185103,104.185060,104.184996,104.184846,104.184781,104.184685,104.184578,104.184454,104.184406,104.184384,104.184374,104.184352,104.184325,104.184304,104.184299,104.184288,104.184277,104.184256,104.184261,104.184245,104.184234,104.184207,104.184197,104.184186,104.184186,104.184170,104.184148,104.184111,104.184095,104.184122,104.184159,104.184181,104.184224,104.184272,104.184309,104.184336,104.184433,104.184508,104.184599,104.184755});
                put("base", new double[]{30.825343, 104.184851});
            }});

**Comment by Foreverddb** [comment]
收到，稍后更新
生成apk的话在Android Studio里工具栏里选择Build->Generate Signed Bundle or Apk即可

**Comment by zzd222** [comment]
你好，请问我怎么没找到app/src/main/java/fucklegym/top/entropy/PathGenerator 这个路径呢，可以发一下完整源码吗

**Comment by Foreverddb** [comment]
目前因为某些原因暂时删除了源码，不过可以通过git记录找到源码

**Comment by zzd222** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Foreverddb/FuckLegym"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Foreverddb/FuckLegym] 西南石油大学地图 (Issue #9)





 
目前因为某些原因暂时删除了源码，不过可以通过git记录找到源码
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XiMoHuanHua** [comment]
> 收到，稍后更新 生成apk的话在Android Studio里工具栏里选择Build->Generate Signed Bundle or Apk即可

**Comment by XiMoHuanHua** [comment]
我在IDEA和Android Studio的build里都找不到Generate Signed Bundle or Apk这个选项，是不是没配置好的原因啊

**Comment by Foreverddb** [comment]
已更新，请在[release](https://github.com/Foreverddb/FuckLegym/releases/)下载最新版
